config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :projects

  get 'search/index'

  resources :experiments

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
	
	belongs_to :project
	
	validates :title, :procedure, :image_url, presence: true
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: { with: %r{\.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG, or PNG image.'
	}
	
	scope :date_started, lambda{|date_started| where('date_started = ?', date_started)}
	scope :project_id, lambda{|project_id| where('project_id = ?', project_id)}
	scope :updated_at, lambda{|updated_at| where('updated_at = ?', updated_at)}
	
	

	

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :experiment
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :experiments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction	
  # GET /experiments
  # GET /experiments.json
  def index
   # @experiments = Experiment.order(date_started: :desc)
	@experiments = Experiment.order("#{params[:sort]} DESC")
  end

  def search
	@experiments = Experiment.search params[:search]
  end
  
  # GET /experiments/1
  # GET /experiments/1.json
  def show
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url, notice: 'Experiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiment_params
      params.require(:experiment).permit(:title, :procedure, :image_url, :date_started)
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:experiment_id, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
	# @experiments = Experiment.order(date_started: :desc)

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
	@experiments = Experiment.order(:date_started)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	

end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/experiments/_form.html.erb
<div class=" viewport ">

<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, rows: 3, :class=>"textbox small" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :procedure %><br>
    <%= f.text_area :procedure, rows: 20, :class=>"textbox large"%><br> 
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, cols: 60, :class=>"textbox small" %>
  </div>
  <div class="field">
    <%= f.label :date_started %><br>
    <%= f.date_select :date_started %>
  </div>
  <div class="field">
	<%= f.collection_select(:project_id, Project.all, :id, :title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/experiments/_formedit.html.erb
<div class=" viewport ">

<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, rows: 3, :class=>"textbox small" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :procedure %><br>
    <%= f.text_area :procedure, rows: 20, :class=>"textbox large"%><br> 
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, cols: 60, :class=>"textbox small" %>
  </div>
  <div class="field">
	<%= f.collection_select(:project_id, Project.all, :id, :title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/experiments/_results.html.erb
<ul>
    <% @experiments.each do |experiment| %>
  <li><%= link_to experiment.title, 
    experiment  %></li>
  <% end %>
 </ul>

app/views/experiments/_search.html.erb
		<%= form_tag experiments_path :method => 'get' do %>
			<%= text_field_tag :search, params[:search]%>
			<%= submit_tag "Search", :name => nil %>
			<%= link_to "Clear", "$('search_field').clear()"%> 
		<% end %>

app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>

<%= render 'formedit' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<div class="viewport">



<h1>Experiments!</h1>


<table>

	<thead>
		<tr> 
			<th><%= link_to "Last Updated", :sort => "updated_at" %></th>
			<th><%= link_to "Date Started", :sort => "date_started"%></th>
			<th> Experiments</th>
			<th> Project</th>
		</tr>
	</thead>
	<tbody>
<% # experiments listing in a table %>
 <% @experiments.each do |experiment| %>
	<tr class="<%= cycle('list_line_odd', 'list_line_even') %> ">
		
		<td class="date">
			<dt>
				<%= experiment.updated_at %>
			</dt>
		</td>
		
		<td class="date">
			<dt>
				<%= experiment.date_started %>
			</dt>
		</td>
		
		<td class="list_description">
			<dl>
				<dt>
					<%= link_to experiment.title, experiment %>
				</dt>
				<dd><%= truncate(strip_tags(experiment.procedure), length:160) %></dd>
			</dl>	
		</td>
		
		<td>
			
			
			<% if not experiment.project.nil? then %>
			<%=experiment.project.title %>
			<% end %>
		</td>
		
		
		
	</tr>
<% end %>
</tbody>	
</table>

<br />

<%= link_to 'New Experiment', new_experiment_path %>

</div>

app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<div class=" viewport ">

<p id="notice"><%= notice %></p>

<p>
  <h2>
  <%= @experiment.title %>
  </h2>
  <%= link_to 'Edit', edit_experiment_path(@experiment) %> |
  <%= link_to 'Back', experiments_path %>
</p>

<p>
  <strong>Date started:</strong>
  <%= @experiment.date_started %>
  <strong>Last Updated:</strong>
  <%= @experiment.updated_at %>
</p>

<p>
  <strong>Scheme:</strong>
  <div class="textbox large">
	<%= image_tag(@experiment.image_url, class: 'list_image') %>
	</div>
</p>

<p>
  <strong>Procedure:</strong><br>
  <div class="textbox large">
	<%= strip_tags(@experiment.procedure) %>
	</div>
  	
</p>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blabnotes2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body class= "experiments">
	
	<div class="topnav">
	<h1 class="logo"> Blabnotes</h1>
	</div>

	<div class="sidebar">
		<ul>
			<li> 
			<%= link_to 'Projects', "projects" %>
			</li>
			<li> 
			<%= link_to 'Experiments', "experiments" %>
			</li>
			<li>
				<%= link_to 'New Project', new_project_path %>
			</li>
			<li>
				<%= link_to 'New Experiment', new_experiment_path %>
			</li>
			<br>
			<br>
		</ul>
	
		
		
		
	</div>


<%= yield %>

</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :experiment_id %><br>
    <%= f.text_field :experiment_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Experiment</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.experiment %></td>
        <td><%= line_item.project %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Experiment:</strong>
  <%= @line_item.experiment %>
</p>

<p>
  <strong>Project:</strong>
  <%= @line_item.project %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/projects/_form.html.erb
<div class=" viewport ">

<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, rows: 3, :class=>"textbox small" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 20, :class=>"textbox large"%><br> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="viewport">

<h1>Your Projects</h1>



<br>

<table>

<% # projects listing in a table %>
 <% @projects.each do |project| %>
	<tr class="<%= cycle('list_line_odd', 'list_line_even') %> ">
		<td class="list_description">
			<dl>
				<dt>
					<%= link_to project.title, project %>
				</dt>
				<dd><%= truncate(strip_tags(project.description), length:160) %></dd>
			</dl>
			
		</td>
	
	</tr>
<% end %>	
</table>

<%= link_to 'New Project', new_project_path %>

</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class=" viewport ">

<p id="notice"><%= notice %></p>

<p>
  <h2>
  <%= @project.title %>
  </h2>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</p>

<p>
  <strong>Notes:</strong><br>
  <div class="textbox large">
	<%= strip_tags(@project.description) %>
	</div>
  	
</p>

<!-- table list of experiments that belong to this project -->
<table>
<% # experiments listing in a table %>
 <% @project.experiments.each do |experiment| %>
	<tr class="<%= cycle('list_line_odd', 'list_line_even') %> ">
		
		<td class="date">
			<dt>
				<%= experiment.date_started %>
			</dt>
		</td>
		
		
		<td class="list_description">
			<dl>
				<dt>
					<%= link_to experiment.title, experiment %>
				</dt>
				<dd><%= truncate(strip_tags(experiment.procedure), length:160) %></dd>
			</dl>
			
		</td>
	</tr>
<% end %>	
</table>

</div>

app/views/search/index.html.erb
<div class="viewport">

	<h1>Search#index</h1>
	<div class="searchform">
		<%= form_tag experiments_path, :method => 'get' do %>
			<p>
				<%= text_field_tag :search, params[:search] %>
				<%= submit_tag "Search", :name => nil %>
			</p>
		<% end %>
		
	</div>
	
	<br>
	
	#search results go underneath
	
	
	
	
	<!-- 
	<table>

			<% # experiments listing in a table %>
		<% @experiments.each do |experiment| %>
		<tr class="<%= cycle('list_line_odd', 'list_line_even') %> ">
		
			<td class="date">
				<dt>
					<%= experiment.date_started %>
				</dt>
			</td>
		
			<td class="list_description">
				<dl>
					<dt>
						<%= link_to experiment.title, experiment %>
					</dt>
					<dd><%= truncate(strip_tags(experiment.procedure), length:160) %></dd>
				</dl>
			
			</td>
		
		
		</tr>
		<% end %>	
	</table>
	
	-->
	
	
		
		

	
</div>